#include "lang_convert.h"

#include <map>

namespace lge {
namespace mm {

using TableType = std::map<std::string, const char*>;

static TableType s_tbl_ISO_639_1 = {
    { "ab", "Abkhaz" },
    { "aa", "Afar" },
    { "af", "Afrikaans" },
    { "ak", "Akan" },
    { "sq", "Albanian" },
    { "am", "Amharic" },
    { "ar", "Arabic" },
    { "an", "Aragonese" },
    { "hy", "Armenian" },
    { "as", "Assamese" },
    { "av", "Avaric" },
    { "ae", "Avestan" },
    { "ay", "Aymara" },
    { "az", "Azerbaijani" },
    { "bm", "Bambara" },
    { "ba", "Bashkir" },
    { "eu", "Basque" },
    { "be", "Belarusian" },
    { "bn", "Bengali, Bangla" },
    { "bh", "Bihari" },
    { "bi", "Bislama" },
    { "bs", "Bosnian" },
    { "br", "Breton" },
    { "bg", "Bulgarian" },
    { "my", "Burmese" },
    { "ca", "Catalan" },
    { "ch", "Chamorro" },
    { "ce", "Chechen" },
    { "ny", "Chichewa, Chewa, Nyanja" },
    { "zh", "Chinese" },
    { "cv", "Chuvash" },
    { "kw", "Cornish" },
    { "co", "Corsican" },
    { "cr", "Cree" },
    { "hr", "Croatian" },
    { "cs", "Czech" },
    { "da", "Danish" },
    { "dv", "Divehi, Dhivehi, Maldivian" },
    { "nl", "Dutch" },
    { "dz", "Dzongkha" },
    { "en", "English" },
    { "eo", "Esperanto" },
    { "et", "Estonian" },
    { "ee", "Ewe" },
    { "fo", "Faroese" },
    { "fj", "Fijian" },
    { "fi", "Finnish" },
    { "fr", "French" },
    { "ff", "Fula, Fulah, Pulaar, Pular" },
    { "gl", "Galician" },
    { "ka", "Georgian" },
    { "de", "German" },
    { "el", "Greek (modern)" },
    { "gn", "Guarani" },
    { "gu", "Gujarati" },
    { "ht", "Haitian, Haitian Creole" },
    { "ha", "Hausa" },
    { "he", "Hebrew (modern)" },
    { "hz", "Herero" },
    { "hi", "Hindi" },
    { "ho", "Hiri Motu" },
    { "hu", "Hungarian" },
    { "ia", "Interlingua" },
    { "id", "Indonesian" },
    { "ie", "Interlingue" },
    { "ga", "Irish" },
    { "ig", "Igbo" },
    { "ik", "Inupiaq" },
    { "io", "Ido" },
    { "is", "Icelandic" },
    { "it", "Italian" },
    { "iu", "Inuktitut" },
    { "ja", "Japanese" },
    { "jv", "Javanese" },
    { "kl", "Kalaallisut, Greenlandic" },
    { "kn", "Kannada" },
    { "kr", "Kanuri" },
    { "ks", "Kashmiri" },
    { "kk", "Kazakh" },
    { "km", "Khmer" },
    { "ki", "Kikuyu, Gikuyu" },
    { "rw", "Kinyarwanda" },
    { "ky", "Kyrgyz" },
    { "kv", "Komi" },
    { "kg", "Kongo" },
    { "ko", "Korean" },
    { "ku", "Kurdish" },
    { "kj", "Kwanyama, Kuanyama" },
    { "la", "Latin" },
    { "lb", "Luxembourgish, Letzeburgesch" },
    { "lg", "Ganda" },
    { "li", "Limburgish, Limburgan, Limburger" },
    { "ln", "Lingala" },
    { "lo", "Lao" },
    { "lt", "Lithuanian" },
    { "lu", "Luba-Katanga" },
    { "lv", "Latvian" },
    { "gv", "Manx" },
    { "mk", "Macedonian" },
    { "mg", "Malagasy" },
    { "ms", "Malay" },
    { "ml", "Malayalam" },
    { "mt", "Maltese" },
    { "mi", "Maori" },
    { "mr", "Marathi" },
    { "mh", "Marshallese" },
    { "mn", "Mongolian" },
    { "na", "Nauruan" },
    { "nv", "Navajo, Navaho" },
    { "nd", "Northern Ndebele" },
    { "ne", "Nepali" },
    { "ng", "Ndonga" },
    { "nb", "Norwegian" },
    { "nn", "Norwegian Nynorsk" },
    { "no", "Norwegian" },
    { "ii", "Nuosu" },
    { "nr", "Southern Ndebele" },
    { "oc", "Occitan" },
    { "oj", "Ojibwe, Ojibwa" },
    { "cu", "Old Church Slavonic, Church Slavonic, Old Bulgarian" },
    { "om", "Oromo" },
    { "or", "Oriya" },
    { "os", "Ossetian, Ossetic" },
    { "pa", "Panjabi, Punjabi" },
    { "pi", "Pali" },
    { "fa", "Persian (Farsi)" },
    { "pl", "Polish" },
    { "ps", "Pashto, Pushto" },
    { "pt", "Portuguese" },
    { "qu", "Quechua" },
    { "rm", "Romansh" },
    { "rn", "Kirundi" },
    { "rc", "Reunionese, Reunion Creole" },
    { "ro", "Romanian" },
    { "ru", "Russian" },
    { "sa", "Sanskrit" },
    { "sc", "Sardinian" },
    { "sd", "Sindhi" },
    { "se", "Northern Sami" },
    { "sm", "Samoan" },
    { "sg", "Sango" },
    { "sr", "Serbian" },
    { "gd", "Scottish Gaelic, Gaelic" },
    { "sn", "Shona" },
    { "si", "Sinhalese, Sinhala" },
    { "sk", "Slovak" },
    { "sl", "Slovene" },
    { "so", "Somali" },
    { "st", "Southern Sotho" },
    { "es", "Spanish" },
    { "su", "Sundanese" },
    { "sw", "Swahili" },
    { "ss", "Swati" },
    { "sv", "Swedish" },
    { "ta", "Tamil" },
    { "te", "Telugu" },
    { "tg", "Tajik" },
    { "th", "Thai" },
    { "ti", "Tigrinya" },
    { "bo", "Tibetan Standard, Tibetan, Central" },
    { "tk", "Turkmen" },
    { "tl", "Tagalog" },
    { "tn", "Tswana" },
    { "to", "Tonga (Tonga Islands)" },
    { "tr", "Turkish" },
    { "ts", "Tsonga" },
    { "tt", "Tatar" },
    { "tw", "Twi" },
    { "ty", "Tahitian" },
    { "ug", "Uyghur" },
    { "uk", "Ukrainian" },
    { "ur", "Urdu" },
    { "uz", "Uzbek" },
    { "ve", "Venda" },
    { "vi", "Vietnamese" },
    { "vo", "Volapuk" },
    { "wa", "Walloon" },
    { "cy", "Welsh" },
    { "wo", "Wolof" },
    { "fy", "Western Frisian" },
    { "xh", "Xhosa" },
    { "yi", "Yiddish" },
    { "yo", "Yoruba" },
    { "za", "Zhuang, Chuang" },
    { "zu", "Zulu" }
};

static TableType s_tbl_ISO_639_2_T = {
    { "abk", "Abkhaz" },
    { "aar", "Afar" },
    { "afr", "Afrikaans" },
    { "aka", "Akan" },
    { "sqi", "Albanian" },
    { "amh", "Amharic" },
    { "ara", "Arabic" },
    { "arg", "Aragonese" },
    { "hye", "Armenian" },
    { "asm", "Assamese" },
    { "ava", "Avaric" },
    { "ave", "Avestan" },
    { "aym", "Aymara" },
    { "aze", "Azerbaijani" },
    { "bam", "Bambara" },
    { "bak", "Bashkir" },
    { "eus", "Basque" },
    { "bel", "Belarusian" },
    { "ben", "Bengali, Bangla" },
    { "bih", "Bihari" },
    { "bis", "Bislama" },
    { "bos", "Bosnian" },
    { "bre", "Breton" },
    { "bul", "Bulgarian" },
    { "mya", "Burmese" },
    { "cat", "Catalan" },
    { "cha", "Chamorro" },
    { "che", "Chechen" },
    { "nya", "Chichewa, Chewa, Nyanja" },
    { "zho", "Chinese" },
    { "chv", "Chuvash" },
    { "cor", "Cornish" },
    { "cos", "Corsican" },
    { "cre", "Cree" },
    { "hrv", "Croatian" },
    { "ces", "Czech" },
    { "dan", "Danish" },
    { "div", "Divehi, Dhivehi, Maldivian" },
    { "nld", "Dutch" },
    { "dzo", "Dzongkha" },
    { "eng", "English" },
    { "epo", "Esperanto" },
    { "est", "Estonian" },
    { "ewe", "Ewe" },
    { "fao", "Faroese" },
    { "fij", "Fijian" },
    { "fin", "Finnish" },
    { "fra", "French" },
    { "ful", "Fula, Fulah, Pulaar, Pular" },
    { "glg", "Galician" },
    { "kat", "Georgian" },
    { "deu", "German" },
    { "ell", "Greek (modern)" },
    { "grn", "Guarani" },
    { "guj", "Gujarati" },
    { "hat", "Haitian, Haitian Creole" },
    { "hau", "Hausa" },
    { "heb", "Hebrew (modern)" },
    { "her", "Herero" },
    { "hin", "Hindi" },
    { "hmo", "Hiri Motu" },
    { "hun", "Hungarian" },
    { "ina", "Interlingua" },
    { "ind", "Indonesian" },
    { "ile", "Interlingue" },
    { "gle", "Irish" },
    { "ibo", "Igbo" },
    { "ipk", "Inupiaq" },
    { "ido", "Ido" },
    { "isl", "Icelandic" },
    { "ita", "Italian" },
    { "iku", "Inuktitut" },
    { "jpn", "Japanese" },
    { "jav", "Javanese" },
    { "kal", "Kalaallisut, Greenlandic" },
    { "kan", "Kannada" },
    { "kau", "Kanuri" },
    { "kas", "Kashmiri" },
    { "kaz", "Kazakh" },
    { "khm", "Khmer" },
    { "kik", "Kikuyu, Gikuyu" },
    { "kin", "Kinyarwanda" },
    { "kir", "Kyrgyz" },
    { "kom", "Komi" },
    { "kon", "Kongo" },
    { "kor", "Korean" },
    { "kur", "Kurdish" },
    { "kua", "Kwanyama, Kuanyama" },
    { "lat", "Latin" },
    { "ltz", "Luxembourgish, Letzeburgesch" },
    { "lug", "Ganda" },
    { "lim", "Limburgish, Limburgan, Limburger" },
    { "lin", "Lingala" },
    { "lao", "Lao" },
    { "lit", "Lithuanian" },
    { "lub", "Luba-Katanga" },
    { "lav", "Latvian" },
    { "glv", "Manx" },
    { "mkd", "Macedonian" },
    { "mlg", "Malagasy" },
    { "msa", "Malay" },
    { "mal", "Malayalam" },
    { "mlt", "Maltese" },
    { "mri", "Maori" },
    { "mar", "Marathi" },
    { "mah", "Marshallese" },
    { "mon", "Mongolian" },
    { "nau", "Nauruan" },
    { "nav", "Navajo, Navaho" },
    { "nde", "Northern Ndebele" },
    { "nep", "Nepali" },
    { "ndo", "Ndonga" },
    { "nob", "Norwegian" },
    { "nno", "Norwegian Nynorsk" },
    { "nor", "Norwegian" },
    { "iii", "Nuosu" },
    { "nbl", "Southern Ndebele" },
    { "oci", "Occitan" },
    { "oji", "Ojibwe, Ojibwa" },
    { "chu", "Old Church Slavonic, Church Slavonic, Old Bulgarian" },
    { "orm", "Oromo" },
    { "ori", "Oriya" },
    { "oss", "Ossetian, Ossetic" },
    { "pan", "Panjabi, Punjabi" },
    { "pli", "Pali" },
    { "fas", "Persian (Farsi)" },
    { "pol", "Polish" },
    { "pus", "Pashto, Pushto" },
    { "por", "Portuguese" },
    { "que", "Quechua" },
    { "roh", "Romansh" },
    { "run", "Kirundi" },
    { "rcf", "Reunionese, Reunion Creole" },
    { "ron", "Romanian" },
    { "rus", "Russian" },
    { "san", "Sanskrit" },
    { "srd", "Sardinian" },
    { "snd", "Sindhi" },
    { "sme", "Northern Sami" },
    { "smo", "Samoan" },
    { "sag", "Sango" },
    { "srp", "Serbian" },
    { "gla", "Scottish Gaelic, Gaelic" },
    { "sna", "Shona" },
    { "sin", "Sinhalese, Sinhala" },
    { "slk", "Slovak" },
    { "slv", "Slovene" },
    { "som", "Somali" },
    { "sot", "Southern Sotho" },
    { "spa", "Spanish" },
    { "sun", "Sundanese" },
    { "swa", "Swahili" },
    { "ssw", "Swati" },
    { "swe", "Swedish" },
    { "tam", "Tamil" },
    { "tel", "Telugu" },
    { "tgk", "Tajik" },
    { "tha", "Thai" },
    { "tir", "Tigrinya" },
    { "bod", "Tibetan Standard, Tibetan, Central" },
    { "tuk", "Turkmen" },
    { "tgl", "Tagalog" },
    { "tsn", "Tswana" },
    { "ton", "Tonga (Tonga Islands)" },
    { "tur", "Turkish" },
    { "tso", "Tsonga" },
    { "tat", "Tatar" },
    { "twi", "Twi" },
    { "tah", "Tahitian" },
    { "uig", "Uyghur" },
    { "ukr", "Ukrainian" },
    { "urd", "Urdu" },
    { "uzb", "Uzbek" },
    { "ven", "Venda" },
    { "vie", "Vietnamese" },
    { "vol", "Volapuk" },
    { "wln", "Walloon" },
    { "cym", "Welsh" },
    { "wol", "Wolof" },
    { "fry", "Western Frisian" },
    { "xho", "Xhosa" },
    { "yid", "Yiddish" },
    { "yor", "Yoruba" },
    { "zha", "Zhuang, Chuang" },
    { "zul", "Zulu" }
};

static TableType s_tbl_ISO_639_2_B = {
    { "abk", "Abkhaz" },
    { "aar", "Afar" },
    { "afr", "Afrikaans" },
    { "aka", "Akan" },
    { "alb", "Albanian" },
    { "amh", "Amharic" },
    { "ara", "Arabic" },
    { "arg", "Aragonese" },
    { "arm", "Armenian" },
    { "asm", "Assamese" },
    { "ava", "Avaric" },
    { "ave", "Avestan" },
    { "aym", "Aymara" },
    { "aze", "Azerbaijani" },
    { "bam", "Bambara" },
    { "bak", "Bashkir" },
    { "baq", "Basque" },
    { "bel", "Belarusian" },
    { "ben", "Bengali, Bangla" },
    { "bih", "Bihari" },
    { "bis", "Bislama" },
    { "bos", "Bosnian" },
    { "bre", "Breton" },
    { "bul", "Bulgarian" },
    { "bur", "Burmese" },
    { "cat", "Catalan" },
    { "cha", "Chamorro" },
    { "che", "Chechen" },
    { "nya", "Chichewa, Chewa, Nyanja" },
    { "chi", "Chinese" },
    { "chv", "Chuvash" },
    { "cor", "Cornish" },
    { "cos", "Corsican" },
    { "cre", "Cree" },
    { "hrv", "Croatian" },
    { "cze", "Czech" },
    { "dan", "Danish" },
    { "div", "Divehi, Dhivehi, Maldivian" },
    { "dut", "Dutch" },
    { "dzo", "Dzongkha" },
    { "eng", "English" },
    { "epo", "Esperanto" },
    { "est", "Estonian" },
    { "ewe", "Ewe" },
    { "fao", "Faroese" },
    { "fij", "Fijian" },
    { "fin", "Finnish" },
    { "fre", "French" },
    { "ful", "Fula, Fulah, Pulaar, Pular" },
    { "glg", "Galician" },
    { "geo", "Georgian" },
    { "ger", "German" },
    { "gre", "Greek (modern)" },
    { "grn", "Guarani" },
    { "guj", "Gujarati" },
    { "hat", "Haitian, Haitian Creole" },
    { "hau", "Hausa" },
    { "heb", "Hebrew (modern)" },
    { "her", "Herero" },
    { "hin", "Hindi" },
    { "hmo", "Hiri Motu" },
    { "hun", "Hungarian" },
    { "ina", "Interlingua" },
    { "ind", "Indonesian" },
    { "ile", "Interlingue" },
    { "gle", "Irish" },
    { "ibo", "Igbo" },
    { "ipk", "Inupiaq" },
    { "ido", "Ido" },
    { "ice", "Icelandic" },
    { "ita", "Italian" },
    { "iku", "Inuktitut" },
    { "jpn", "Japanese" },
    { "jav", "Javanese" },
    { "kal", "Kalaallisut, Greenlandic" },
    { "kan", "Kannada" },
    { "kau", "Kanuri" },
    { "kas", "Kashmiri" },
    { "kaz", "Kazakh" },
    { "khm", "Khmer" },
    { "kik", "Kikuyu, Gikuyu" },
    { "kin", "Kinyarwanda" },
    { "kir", "Kyrgyz" },
    { "kom", "Komi" },
    { "kon", "Kongo" },
    { "kor", "Korean" },
    { "kur", "Kurdish" },
    { "kua", "Kwanyama, Kuanyama" },
    { "lat", "Latin" },
    { "ltz", "Luxembourgish, Letzeburgesch" },
    { "lug", "Ganda" },
    { "lim", "Limburgish, Limburgan, Limburger" },
    { "lin", "Lingala" },
    { "lao", "Lao" },
    { "lit", "Lithuanian" },
    { "lub", "Luba-Katanga" },
    { "lav", "Latvian" },
    { "glv", "Manx" },
    { "mac", "Macedonian" },
    { "mlg", "Malagasy" },
    { "may", "Malay" },
    { "mal", "Malayalam" },
    { "mlt", "Maltese" },
    { "mao", "Maori" },
    { "mar", "Marathi" },
    { "mah", "Marshallese" },
    { "mon", "Mongolian" },
    { "nau", "Nauruan" },
    { "nav", "Navajo, Navaho" },
    { "nde", "Northern Ndebele" },
    { "nep", "Nepali" },
    { "ndo", "Ndonga" },
    { "nob", "Norwegian" },
    { "nno", "Norwegian Nynorsk" },
    { "nor", "Norwegian" },
    { "iii", "Nuosu" },
    { "nbl", "Southern Ndebele" },
    { "oci", "Occitan" },
    { "oji", "Ojibwe, Ojibwa" },
    { "chu", "Old Church Slavonic, Church Slavonic, Old Bulgarian" },
    { "orm", "Oromo" },
    { "ori", "Oriya" },
    { "oss", "Ossetian, Ossetic" },
    { "pan", "Panjabi, Punjabi" },
    { "pli", "Pali" },
    { "per", "Persian (Farsi)" },
    { "pol", "Polish" },
    { "pus", "Pashto, Pushto" },
    { "por", "Portuguese" },
    { "que", "Quechua" },
    { "roh", "Romansh" },
    { "run", "Kirundi" },
    { "rcf", "Reunionese, Reunion Creole" },
    { "rum", "Romanian" },
    { "rus", "Russian" },
    { "san", "Sanskrit" },
    { "srd", "Sardinian" },
    { "snd", "Sindhi" },
    { "sme", "Northern Sami" },
    { "smo", "Samoan" },
    { "sag", "Sango" },
    { "srp", "Serbian" },
    { "gla", "Scottish Gaelic, Gaelic" },
    { "sna", "Shona" },
    { "sin", "Sinhalese, Sinhala" },
    { "slo", "Slovak" },
    { "slv", "Slovene" },
    { "som", "Somali" },
    { "sot", "Southern Sotho" },
    { "spa", "Spanish" },
    { "sun", "Sundanese" },
    { "swa", "Swahili" },
    { "ssw", "Swati" },
    { "swe", "Swedish" },
    { "tam", "Tamil" },
    { "tel", "Telugu" },
    { "tgk", "Tajik" },
    { "tha", "Thai" },
    { "tir", "Tigrinya" },
    { "tib", "Tibetan Standard, Tibetan, Central" },
    { "tuk", "Turkmen" },
    { "tgl", "Tagalog" },
    { "tsn", "Tswana" },
    { "ton", "Tonga (Tonga Islands)" },
    { "tur", "Turkish" },
    { "tso", "Tsonga" },
    { "tat", "Tatar" },
    { "twi", "Twi" },
    { "tah", "Tahitian" },
    { "uig", "Uyghur" },
    { "ukr", "Ukrainian" },
    { "urd", "Urdu" },
    { "uzb", "Uzbek" },
    { "ven", "Venda" },
    { "vie", "Vietnamese" },
    { "vol", "Volapuk" },
    { "wln", "Walloon" },
    { "wel", "Welsh" },
    { "wol", "Wolof" },
    { "fry", "Western Frisian" },
    { "xho", "Xhosa" },
    { "yid", "Yiddish" },
    { "yor", "Yoruba" },
    { "zha", "Zhuang, Chuang" },
    { "zul", "Zulu" }
};

std::string LangConvert::ISO639ToEnglishName(const std::string& iso639) {
    TableType::iterator it;

    it = s_tbl_ISO_639_1.find(iso639);
    if (it != s_tbl_ISO_639_1.end()) {
        return (it->second ? it->second : "");
    }

    it = s_tbl_ISO_639_2_T.find(iso639);
    if (it != s_tbl_ISO_639_2_T.end()) {
        return (it->second ? it->second : "");
    }

    it = s_tbl_ISO_639_2_B.find(iso639);
    if (it != s_tbl_ISO_639_2_B.end()) {
        return (it->second ? it->second : "");
    }

    return "";
}

} // namespace mm
} // namespace lge

